name: sails_io
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/sailscastshq/sails_io

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  socket_io_client: ^1.0.1

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
