name: sails_io
version: 0.0.1
homepage: https://github.com/sailscastshq/sails_io
description: Dart/Flutter Websocket Client SDK for communication with Sails from a mobile application.
environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  socket_io_client: ^1.0.1

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
